"""initial_schema

Revision ID: 2b32241187b3
Revises: 
Create Date: 2026-06-25 00:13:23.989207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b32241187b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompt_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('crm_child_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('parent_entity_type_id', sa.Integer(), nullable=True),
    sa.Column('parent_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'record_type', 'external_id', name='uq_crm_child')
    )
    op.create_index('ix_crm_child_parent', 'crm_child_records', ['portal_id', 'parent_entity_type_id', 'parent_entity_id'], unique=False)
    op.create_table('crm_currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'currency_code', name='uq_crm_currency')
    )
    op.create_table('crm_dictionaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=True),
    sa.Column('dictionary_code', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_dictionary_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dictionary_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('xml_id', sa.String(length=255), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('semantic_group', sa.String(length=128), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dictionary_id', 'external_id', name='uq_dict_entry')
    )
    op.create_index(op.f('ix_crm_dictionary_entries_dictionary_id'), 'crm_dictionary_entries', ['dictionary_id'], unique=False)
    op.create_table('crm_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('currency_id', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'entity_type_id', 'entity_id', name='uq_crm_entity')
    )
    op.create_index(op.f('ix_crm_entities_is_deleted'), 'crm_entities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_crm_entities_payload_hash'), 'crm_entities', ['payload_hash'], unique=False)
    op.create_index('ix_crm_entities_portal_type_updated', 'crm_entities', ['portal_id', 'entity_type_id', 'updated_time', 'entity_id'], unique=False)
    op.create_table('crm_entity_field_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value_index', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('date_value', sa.DateTime(timezone=True), nullable=True),
    sa.Column('datetime_value', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dictionary_entry_id', sa.Integer(), nullable=True),
    sa.Column('related_entity_type_id', sa.Integer(), nullable=True),
    sa.Column('related_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('value_hash', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_entity_field_values_field_definition_id'), 'crm_entity_field_values', ['field_definition_id'], unique=False)
    op.create_table('crm_entity_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_source', sa.String(length=32), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_field_definition_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_field_definition_versions_field_definition_id'), 'crm_field_definition_versions', ['field_definition_id'], unique=False)
    op.create_table('crm_field_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('original_field_name', sa.String(length=255), nullable=False),
    sa.Column('api_field_name', sa.String(length=255), nullable=False),
    sa.Column('upper_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('list_label', sa.String(length=512), nullable=True),
    sa.Column('form_label', sa.String(length=512), nullable=True),
    sa.Column('filter_label', sa.String(length=512), nullable=True),
    sa.Column('field_type', sa.String(length=64), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('is_multiple', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_read_only', sa.Boolean(), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('raw_definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'entity_type_id', 'original_field_name', name='uq_crm_field_def')
    )
    op.create_table('crm_field_semantics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('business_purpose', sa.Text(), nullable=True),
    sa.Column('normalized_data_type', sa.String(length=64), nullable=True),
    sa.Column('data_category', sa.String(length=32), nullable=True),
    sa.Column('is_dictionary', sa.Boolean(), nullable=False),
    sa.Column('dictionary_kind', sa.String(length=32), nullable=True),
    sa.Column('nullable_description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_field_semantics_field_definition_id'), 'crm_field_semantics', ['field_definition_id'], unique=False)
    op.create_index(op.f('ix_crm_field_semantics_source_hash'), 'crm_field_semantics', ['source_hash'], unique=False)
    op.create_table('crm_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('bitrix_file_id', sa.String(length=64), nullable=False),
    sa.Column('disk_object_id', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('parent_entity_type_id', sa.Integer(), nullable=True),
    sa.Column('parent_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('download_status', sa.String(length=32), nullable=False),
    sa.Column('raw_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'bitrix_file_id', name='uq_crm_file')
    )
    op.create_table('crm_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=True),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'external_id', name='uq_crm_user')
    )
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=False),
    sa.Column('result_file', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('statistics_json', sa.Text(), nullable=False),
    sa.Column('event_log_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('resource_name', sa.String(length=64), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('cursor_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor_id', sa.BigInteger(), nullable=True),
    sa.Column('last_successful_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reconciliation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_id', 'resource_name', 'entity_type_id', name='uq_sync_checkpoint')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portal_id', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('current_phase', sa.String(length=128), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('unchanged_count', sa.Integer(), nullable=False),
    sa.Column('deleted_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('api_requests_count', sa.Integer(), nullable=False),
    sa.Column('ai_requests_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('statistics_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_portal_id'), 'sync_runs', ['portal_id'], unique=False)
    op.create_index('ix_sync_runs_portal_mode_active', 'sync_runs', ['portal_id', 'mode'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index('ix_sync_runs_portal_mode_active', table_name='sync_runs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index(op.f('ix_sync_runs_portal_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_table('sync_checkpoints')
    op.drop_table('export_jobs')
    op.drop_table('crm_users')
    op.drop_table('crm_files')
    op.drop_index(op.f('ix_crm_field_semantics_source_hash'), table_name='crm_field_semantics')
    op.drop_index(op.f('ix_crm_field_semantics_field_definition_id'), table_name='crm_field_semantics')
    op.drop_table('crm_field_semantics')
    op.drop_table('crm_field_definitions')
    op.drop_index(op.f('ix_crm_field_definition_versions_field_definition_id'), table_name='crm_field_definition_versions')
    op.drop_table('crm_field_definition_versions')
    op.drop_table('crm_entity_versions')
    op.drop_index(op.f('ix_crm_entity_field_values_field_definition_id'), table_name='crm_entity_field_values')
    op.drop_table('crm_entity_field_values')
    op.drop_index('ix_crm_entities_portal_type_updated', table_name='crm_entities')
    op.drop_index(op.f('ix_crm_entities_payload_hash'), table_name='crm_entities')
    op.drop_index(op.f('ix_crm_entities_is_deleted'), table_name='crm_entities')
    op.drop_table('crm_entities')
    op.drop_index(op.f('ix_crm_dictionary_entries_dictionary_id'), table_name='crm_dictionary_entries')
    op.drop_table('crm_dictionary_entries')
    op.drop_table('crm_dictionaries')
    op.drop_table('crm_currencies')
    op.drop_index('ix_crm_child_parent', table_name='crm_child_records')
    op.drop_table('crm_child_records')
    op.drop_table('app_settings')
    op.drop_table('ai_prompt_templates')
    # ### end Alembic commands ###
